# Generated by Django 2.2.1 on 2019-05-17 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Apensamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apensamento', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=255)),
                ('data_validade', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(choices=[('S', 'Sigiloso'), ('N', 'Normal'), ('A', 'Administrativo')], max_length=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('apensamento', models.ManyToManyField(through='processos.Apensamento', to='processos.Processo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Interessado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
                ('cpf', models.CharField(max_length=14)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Advogado')),
            ],
        ),
        migrations.AddField(
            model_name='apensamento',
            name='processo_apensado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='processos.Processo'),
        ),
        migrations.AddField(
            model_name='apensamento',
            name='processo_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='processos.Processo'),
        ),
        migrations.AddField(
            model_name='advogado',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Registro'),
        ),
    ]
