# Generated by Django 2.2.1 on 2019-05-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_processo_interessados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='interessados',
            field=models.ManyToManyField(related_name='processo_interessado', to='processos.Interessado'),
        ),
    ]
