# Generated by Django 2.2.1 on 2019-05-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_auto_20190517_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='interessados',
            field=models.ManyToManyField(to='processos.Interessado'),
        ),
    ]
